# =============================================================================
# Copyright (c) 2020, 2026 THALES GLOBAL SERVICES.
# 
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
# 
# SPDX-License-Identifier: EPL-2.0
# 
# Contributors:
#    Thales - initial API and implementation
# =============================================================================
featureName = Connector for Capella and Simulink® Core
providerName = Eclipse.org
description = Connector for Capella and Simulink® core feature
copyright=\
Copyright (c) 2020, 2026 THALES GLOBAL SERVICES.\n\
\n\
This program and the accompanying materials are made available under the\n\
terms of the Eclipse Public License 2.0 which is available at\n\
http://www.eclipse.org/legal/epl-2.0\n\
\n\
SPDX-License-Identifier: EPL-2.0\n\
\n\
Contributors:\n\
    Thales - initial API and implementation\n
